name: Deploy Phase 3 Backend to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: todo_AI_chatbot
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot"

          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME_PHASE3 hf

          rm -rf hf/*
          cp -r Phase_3_Todo_AI_Chatbot/backend/* hf/

          cd hf
          git add .
          git commit -m "Deploy Phase 3 Backend" || echo "No changes"
          git push
